pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        
        stage("Checkout") {
            steps{                
                // manual checkout, for testing Jenkinsfile
                // I creat new pipeline job, definition = pipeline script, copy and paste this file
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'Checkout-Dir']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/devuserPP/simple-java-maven-app.git']]])
                echo "checkout done"           
            }
        }
        
        
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
